\usepackage{titling}

\pretitle{
    \thispagestyle{empty}
    \begin{center}
    \includegraphics[scale=2]{ksu-logo.png}
    \LARGE
    \vfill
}

\posttitle{
    \par
    \end{center}
    \vfill
}

\postauthor{
    \par
    \end{tabular}
    \vfill
    \endgroup
}

\postdate{
    \par
    \end{center}
    \clearpage
}

\renewcommand{\and}{\\}

\title{CS Student Portal \\ Specification document}
\author{Filip Marek \and Ian Riley \and Dominik Sivák \and Andrew Weber}
\date{15 February 2019}